name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v .

  push:
    name: Push artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image
      run: docker build -t docker.pkg.github.com/aku105/jq-in-go/app:1.0 .
    - name: Push docker image
      run: docker push docker.pkg.github.com/aku105/jq-in-go/app:1.0
